In [6]:
import torch as tc

# 1 Making random tensor:-------------------
tc.rand(5)
tc.rand(10).numpy()

array([0.66738987, 0.9777037 , 0.45395446, 0.5301901 , 0.03547311,
       0.18578017, 0.8583889 , 0.36249352, 0.20142579, 0.13796115],
      dtype=float32)

In [8]:
# 2 Shape of the tensor:--------------------
tc.rand(19).shape
tc.rand(19).numpy().shape

(19,)

In [9]:
# 3 Reshaping 6x10:-------------------------
tc.rand(60).reshape((6,10))

tensor([[0.7004, 0.7959, 0.9531, 0.4753, 0.6075, 0.4575, 0.3031, 0.8824, 0.5021,
         0.6939],
        [0.9010, 0.8240, 0.6793, 0.6363, 0.8306, 0.1943, 0.3076, 0.1357, 0.2766,
         0.1707],
        [0.9325, 0.1258, 0.8545, 0.3613, 0.9838, 0.7362, 0.7177, 0.1931, 0.5414,
         0.0734],
        [0.4442, 0.6884, 0.5868, 0.6348, 0.5869, 0.9787, 0.9085, 0.2643, 0.5659,
         0.0423],
        [0.2794, 0.4368, 0.5770, 0.8729, 0.3854, 0.3341, 0.0457, 0.3998, 0.0692,
         0.2551],
        [0.2365, 0.7020, 0.6406, 0.4629, 0.3890, 0.1275, 0.0104, 0.9198, 0.6587,
         0.8836]])

In [15]:
# 4 Making the integer random tensor of size = 10
tc.randint(10, size=(10,4,3))
tc.randint(10, size=(1,))

tensor([2])

In [17]:
tn_6_10=tc.rand(60).reshape((6,10))
tn_10=tc.randint(10, size=(10,))
print(tn_6_10,tn_10)

tensor([[0.7445, 0.0933, 0.1087, 0.6215, 0.5904, 0.8370, 0.1863, 0.9411, 0.0631,
         0.4011],
        [0.3699, 0.6541, 0.5289, 0.3324, 0.0602, 0.4340, 0.6898, 0.3352, 0.8420,
         0.5257],
        [0.4075, 0.9910, 0.4540, 0.1868, 0.0143, 0.8039, 0.1071, 0.8299, 0.2793,
         0.5003],
        [0.3267, 0.6043, 0.5183, 0.0903, 0.8360, 0.2240, 0.6105, 0.3607, 0.3120,
         0.7878],
        [0.3302, 0.2988, 0.0546, 0.4497, 0.2168, 0.1869, 0.3965, 0.4669, 0.2590,
         0.0493],
        [0.7808, 0.8077, 0.2409, 0.5226, 0.2464, 0.3789, 0.3613, 0.6669, 0.9281,
         0.9861]]) tensor([0, 6, 6, 8, 0, 1, 4, 4, 8, 2])


In [18]:
# 5 Element multiplication:------------
tn_6_10*tn_10

tensor([[0.0000, 0.5597, 0.6523, 4.9718, 0.0000, 0.8370, 0.7452, 3.7645, 0.5049,
         0.8023],
        [0.0000, 3.9248, 3.1733, 2.6595, 0.0000, 0.4340, 2.7592, 1.3410, 6.7362,
         1.0514],
        [0.0000, 5.9457, 2.7242, 1.4945, 0.0000, 0.8039, 0.4284, 3.3195, 2.2341,
         1.0006],
        [0.0000, 3.6257, 3.1095, 0.7222, 0.0000, 0.2240, 2.4420, 1.4427, 2.4959,
         1.5757],
        [0.0000, 1.7930, 0.3276, 3.5975, 0.0000, 0.1869, 1.5860, 1.8677, 2.0720,
         0.0985],
        [0.0000, 4.8462, 1.4451, 4.1807, 0.0000, 0.3789, 1.4451, 2.6675, 7.4244,
         1.9722]])

In [23]:
# 6 Matrix multiplication:--------------
tn_6_10@(tn_10.float())
tn_6_10.matmul(tn_10.float())

tensor([12.8378, 22.0792, 17.9509, 15.6376, 11.5292, 24.3602])

In [25]:
# 7 calculating diff from:--------------

x = torch.tensor([2.], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.], requires_grad=True)

y = x**3 + z - 75*t
y.backward()
print (x.grad,z.grad,t.grad)

tensor([12.]) tensor([1.]) tensor([-75.])


In [27]:
# 8-9 numerical vector:-----------------
x = tc.ones((5,6))
x.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)