In [13]:
import copy
import tensorflow as tf
from keras.layers import LSTM, SimpleRNN, SimpleRNNCell
from keras.models import Sequential
import numpy as np


In [3]:
tf.random.set_seed(8)

In [7]:
non_recursive = Sequential([
    SimpleRNN(units=2,activation='sigmoid',return_sequences=False,input_shape=(10,1))
])
# units	Positive integer, dimensionality of the output space.
# return_sequences	Boolean. Whether to return the last output in the output sequence, or the full sequence

# https://www.tensorflow.org/api_docs/python/tf/keras/layers/SimpleRNN

non_recursive.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_2 (SimpleRNN)    (None, 2)                 8         
                                                                 
Total params: 8 (32.00 Byte)
Trainable params: 8 (32.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [8]:
non_recursive.get_weights()

[array([[-0.43690532, -0.81241655]], dtype=float32),
 array([[-0.1733135 ,  0.9848667 ],
        [ 0.9848667 ,  0.17331356]], dtype=float32),
 array([0., 0.], dtype=float32)]

In [11]:
np.random.seed(8)
x = np.random.randn(10).reshape((10,1))
non_recursive.predict(x[None])

1/1 [==============================] - 0s 380ms/step


array([[0.47902554, 0.4311265 ]], dtype=float32)

In [12]:
recursive = Sequential([
    SimpleRNN(units=2,activation='sigmoid',return_sequences=True,input_shape=(10,1))
])
recursive.predict(x[None])

1/1 [==============================] - 0s 127ms/step


array([[[0.51922894, 0.5038543 ],
        [0.824091  , 0.4545056 ],
        [0.32418156, 0.3598285 ],
        [0.31653842, 0.37579778],
        [0.17634498, 0.33657455],
        [0.9075553 , 0.5304528 ],
        [0.9216533 , 0.49774984],
        [0.9465071 , 0.5266477 ],
        [0.84745175, 0.46162087],
        [0.85275316, 0.47917882]]], dtype=float32)

In [17]:
# RNN simple

def sigmoid (x):
    output = 1.0/(1.0+np.exp(-x))
    return output

def sigmoid_deriv(sigmoid_output):
    return sigmoid_output*(1-sigmoid_output)

int_to_binary ={}
binary_size = 4

largest_number = pow(2,binary_size)
binary = np.unpackbits(np.array([np.arange(largest_number, dtype=np.uint8)]).T,axis=1)

for i in range(largest_number):
    int_to_binary[i] = binary[i]

display(int_to_binary);

{0: array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 1: array([0, 0, 0, 0, 0, 0, 0, 1], dtype=uint8),
 2: array([0, 0, 0, 0, 0, 0, 1, 0], dtype=uint8),
 3: array([0, 0, 0, 0, 0, 0, 1, 1], dtype=uint8),
 4: array([0, 0, 0, 0, 0, 1, 0, 0], dtype=uint8),
 5: array([0, 0, 0, 0, 0, 1, 0, 1], dtype=uint8),
 6: array([0, 0, 0, 0, 0, 1, 1, 0], dtype=uint8),
 7: array([0, 0, 0, 0, 0, 1, 1, 1], dtype=uint8),
 8: array([0, 0, 0, 0, 1, 0, 0, 0], dtype=uint8),
 9: array([0, 0, 0, 0, 1, 0, 0, 1], dtype=uint8),
 10: array([0, 0, 0, 0, 1, 0, 1, 0], dtype=uint8),
 11: array([0, 0, 0, 0, 1, 0, 1, 1], dtype=uint8),
 12: array([0, 0, 0, 0, 1, 1, 0, 0], dtype=uint8),
 13: array([0, 0, 0, 0, 1, 1, 0, 1], dtype=uint8),
 14: array([0, 0, 0, 0, 1, 1, 1, 0], dtype=uint8),
 15: array([0, 0, 0, 0, 1, 1, 1, 1], dtype=uint8)}

In [18]:
learning_rate = 1
input_dim = 2
hidden_dim = 16
output_dim = 1

weights_0 = np.random.random((input_dim,hidden_dim))
weights_1 = np.random.random((hidden_dim,output_dim))
weights_h = np.random.random((hidden_dim,hidden_dim))

delta_w0 = np.zeros_like(weights_0)
delta_w1 = np.zeros_like(weights_1)
delta_wh = np.zeros_like(weights_h)

# не разобрано


